data:
    max_ctrlPts: 10
    max_kv: 10
    max_faces: 50
    feature_dim: 64
    
model:
    type: "simple"
    dropout: 0.1
    patch_size: 1
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    # resamp_with_conv: True

training:
    batch_size: 256
    n_epochs: 500
    n_iters: 5000000
    snapshot_freq: 1000
    validation_freq: 1000

sampling:
    batch_size: 20
    last_only: True

optim:
    weight_decay: 0.00001
    optimizer: "Adam"
    lr: 0.00005
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 5.0
